### ISSUE TITLE
Scrobbling on iTunes 12.2

### ISSUE THREAD

**Issue by Zifius** [rurza/NepTunes#1]
Unless I'm missing something (just installed the app) scrobbling currently doesn't work with the latest iTunes version

Anyway I help, logs etc?

Thank you!

**Comment by Bilalh** [comment]
Works for me on iTunes 12.2. Even works with Apple Music. Did you open the app?

**Comment by Zifius** [comment]
Yes opened and logged in. Perhaps I did something wrong as it was first
time I used the app

**Comment by Zifius** [comment]
@Bilalh just tried again and no dice.. do you get "Now Playing" when you start a song in iTunes?

**Comment by Bilalh** [comment]
More specifically  It only work when playing music  from the 'My Music`  or `Playlist` tab

**Comment by Zifius** [comment]
Yeah, works now, thanks for the tip! But you said it also works for the Apple Music?

**Comment by Bilalh** [comment]
apple music that  added to a playlist

**Comment by Zifius** [comment]
Gotcha... Anyways, thanks for the tips. Hopefully it's possible to scrobble it directly

**Comment by rurza** [comment]
It is but iTunes 12.2 has a bug :)
