### ISSUE TITLE
Neptunes not able to start

### ISSUE THREAD

**Issue by chrisdrackett** [rurza/NepTunes#19]
This might have to do with a recent macOS update (I'm on 10.14.3).

When I try and launch the app when iTunes is open it will not launch. I see the following in console:

https://cl.ly/99be8e996d75

I've checked in Security and Privacy settings and Neptunes should have access to iTunes (its checked)

I'm not sure next steps. I'm able to open Neptunes when iTunes is closed, but after opening iTunes and playing music it is clear that the two are not connected.

**Comment by rurza** [comment]
Hey!

What version of iTunes do you have?

**Comment by chrisdrackett** [comment]
running `12.9.2.5`

**Comment by chrisdrackett** [comment]
as far as I can tell this isn't a neptune thing, as even with apple script I can't seem to control iTunes. Any ideas as to how to fix this?

**Comment by chrisdrackett** [comment]
so I ended up just wiping my system and starting over and this has gone away. I'm sure this was not related to this app, so I'm going to close this issue!
