### ISSUE TITLE
Does not work with Music.app on 10.15 Catalina

### ISSUE THREAD

**Issue by jaknudsen** [rurza/NepTunes#26]
I guess NepTunes expect to find iTunes.app, which no longer exists.

**Comment by Movisivi** [comment]
that's a shame, looks like I won't be upgrading

**Comment by ignaciobarrena** [comment]
I tried reaching the developer via twitter, but he hasn't responded me. I hope that he can update it just to support macOS Catalina's Music App.

**Comment by jbwharris** [comment]
I'm not sure why, but there's a second repo that he did confirm he was working on a new version of the software. 

https://github.com/rurza/NepTunes-Issues/issues/59#issuecomment-525627517

**Comment by Movisivi** [comment]
Since @rurza has been afk for a while, here's a working app https://github.com/yungtry/CatalinaScrobbler 

using on 19A602 right now.

**Comment by rurza** [comment]
NepTunes 1.70 with Music.app released :)
