### ISSUE TITLE
Scrobbling doesn't work with Apple Music

### ISSUE THREAD

**Issue by ravicious** [rurza/NepTunes#4]
How I expect it to work:

1. Open some album in the web version of iTunes, let's say [this one](https://itun.es/pl/Elw97).
2. Click on "View in iTunes".
3. In desktop iTunes, double-click on a particular track.
4. NepTunes starts scrobbling this track to Last.fm.

What happens:

After playing the track from Apple Music, NepTunes doesn't scrobble anything. Although if I add that particular album to my music, everything works fine.

iTunes 12.2.1.16, OS X 10.10.4, NepTunes 0.94.

**Comment by rurza** [comment]
Right now I'm waiting for next iTunes update, because this issue is related with [iTunes 12.2 bug](http://www.openradar.me/21625528). If the Apple doesn't fix this bug in next update I will rewrite the app.
