### ISSUE TITLE
iTunes radio

### ISSUE THREAD

**Issue by alehandrof** [rurza/NepTunes#5]
Is support for iTunes radio a possibility?

**Comment by alehandrof** [comment]
Maybe it's related to #1? I'm not using Apple Music, just listening to Beats 1. But maybe it's technically the same.

**Comment by rurza** [comment]
should be fine now :) Check out newest update on the App Store :)

**Comment by alehandrof** [comment]
I'm having trouble connecting to iTunes radio so I can't confirm at the moment. Because I'm travelling the issue might have to do with my network.

**Comment by alehandrof** [comment]
I got iTunes working by logging in and out. No scrobbling, though.

**Comment by rurza** [comment]
There are some issues with Last.fm related to their migration to new page :(
Proof:
<img width="1280" alt="screenshot 2015-08-23 21 01 11" src="https://cloud.githubusercontent.com/assets/2467137/9429696/26cc2708-49da-11e5-9c3e-b0db23e4b032.png">

**Comment by alehandrof** [comment]
I thought that might be the problem. Do you want to close this issue? I can open a new one if the problem persists after Last.fm has settled down a bit.

**Comment by rurza** [comment]
sure :)
