### ISSUE TITLE
Username is lowercase

### ISSUE THREAD

**Issue by Zifius** [rurza/NepTunes#6]
Hi,

first of all thanks for the resent release to AppStore! Now iTunes experience is much better

Issue here is that in menu username is lowercased, e.g. mine 'NightThief' displays as 'nightthief'. By having a quick look into the code seems that LastFm framework stores it like this internally. Will you accept a PR which will store the username to plist file or maybe there are a better ways to implement?

Best,
Alex

**Comment by rurza** [comment]
sure, I can fix this :) W8 for next update :)

**Comment by Zifius** [comment]
You don't leave me a chance to send my first Objective C PR ;) Thanks!

**Comment by rurza** [comment]
solved in upcoming update (need to log out)
